### ISSUE TITLE
node 10 compatibility 

### ISSUE THREAD

**Issue by vladikoff** [dannycoates/scrypt-hash#18]
Installing it in the fxa-auth-server, currently getting this: 

```
➜  fxa-auth-server git:(master) nvm use 10
Now using node v10.14.2 (npm v6.4.1)
➜  fxa-auth-server git:(master) npm ci 
npm WARN prepare removing existing node_modules/ before installation

> scrypt-hash@1.1.14 install /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/scrypt-hash
> node-gyp rebuild

  CC(target) Release/obj.target/scrypt/crypto_scrypt-sse.o
  CXX(target) Release/obj.target/scrypt/node_scrypt.o
In file included from ../node_scrypt.cc:3:
In file included from ../node_modules/nan/nan.h:190:
../node_modules/nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../node_scrypt.cc:3:
../node_modules/nan/nan.h:816:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/vladikoff/.node-gyp/10.14.2/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/vladikoff/.node-gyp/10.14.2/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../node_scrypt.cc:3:
../node_modules/nan/nan.h:830:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/vladikoff/.node-gyp/10.14.2/include/node/node.h:169:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/vladikoff/.node-gyp/10.14.2/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../node_scrypt.cc:3:
../node_modules/nan/nan.h:844:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/vladikoff/.node-gyp/10.14.2/include/node/node.h:162:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/vladikoff/.node-gyp/10.14.2/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../node_scrypt.cc:3:
../node_modules/nan/nan.h:1447:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/vladikoff/.node-gyp/10.14.2/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/vladikoff/.node-gyp/10.14.2/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
../node_scrypt.cc:137:15: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
        N = info[2]->Uint32Value();
                     ^
/Users/vladikoff/.node-gyp/10.14.2/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
  ^
/Users/vladikoff/.node-gyp/10.14.2/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../node_scrypt.cc:138:15: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
        r = info[3]->Uint32Value();
                     ^
/Users/vladikoff/.node-gyp/10.14.2/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
  ^
/Users/vladikoff/.node-gyp/10.14.2/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../node_scrypt.cc:139:15: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
        p = info[4]->Uint32Value();
                     ^
/Users/vladikoff/.node-gyp/10.14.2/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
  ^
/Users/vladikoff/.node-gyp/10.14.2/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../node_scrypt.cc:140:21: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
        buf_len = info[5]->Uint32Value();
                           ^
/Users/vladikoff/.node-gyp/10.14.2/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
  ^
/Users/vladikoff/.node-gyp/10.14.2/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
8 warnings and 1 error generated.
make: *** [Release/obj.target/scrypt/node_scrypt.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/vladikoff/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/vladikoff/.nvm/versions/node/v10.14.2/bin/node" "/Users/vladikoff/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/scrypt-hash
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt-hash@1.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt-hash@1.1.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vladikoff/.npm/_logs/2019-01-21T20_17_37_777Z-debug.log
```

Could be related: https://github.com/dannycoates/scrypt-hash/issues/15

**Comment by vladikoff** [comment]
i'm guessing the answer is to use node 10's native scrypt
